version: '3.9'
services:
  db:
    image: 'postgres:14-alpine'
    container_name: db
    restart: always
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: book_keeper_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'
  web:
    build: .
    container_name: web
    command: mix phx.server
    environment:
      MIX_ENV: dev
      PORT: 4000
    volumes:
      - .:/app
    ports:
      - '4000:4000'
    depends_on:
      - db
      - adminer
volumes:
  db-data: